### ISSUE TITLE
Action buttons in Rounds page don't work due to validation error

### ISSUE THREAD

**Issue by thrichter** [geziefer/tgiu2#30]
The trash button and the export to Excel buttons do not work.
Both commands seem to fail due to the validation of the mandatory fields for the save button.

![grafik](https://user-images.githubusercontent.com/35894044/103179863-76c45180-4890-11eb-833d-545938b68d15.png)

**Comment by geziefer** [comment]
Hi Thorsten,

ich hab das mal lokal nachgestellt und das kommt von deinem neuen Schalter. Der muss einfach in ein <h:panelGrid> statt einem <p:panelGrid>, probier das mal aus. (Ich weiß nicht exakt, was PrimeFaces da anders macht, aber ich schätze es geht um die Art des Calls und welche Bereiche dann validiert sein müssen.).

Gruß
Alex

Von: Thorsten Richter <notifications@github.com>
Gesendet: Sonntag, 27. Dezember 2020 22:12
An: geziefer/tgiu2 <tgiu2@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [geziefer/tgiu2] Action buttons in Rounds page don't work due to validation error (#30)


The trash button and the export to Excel buttons do not work.
Both commands seem to fail due to the validation of the mandatory fields for the save button.

[grafik]<https://user-images.githubusercontent.com/35894044/103179863-76c45180-4890-11eb-833d-545938b68d15.png>

**Comment by thrichter** [comment]
Fixed and deployed
